apiVersion: v1
kind: Service
metadata:
  name: clb-usermgmt-restapp-service
  labels: 
    app: usermgmt-restapp
  namespace: dev3  
spec:
  type: LoadBalancer # Default - CLB
  selector:
    app: usermgmt-restapp
  ports: 
    - port: 80
      targetPort: 8095           
