apiVersion: v1
kind: Service
metadata:
  name: hpa-demo-cip-service
  labels:
    app: hpa-nginx
spec:
  type: ClusterIP
  selector:
    app: hpa-nginx
  ports:
  - port: 80 # Service Port
    targetPort: 80 # Container Port

  
